#!/usr/bin/env bash
# Fail if common release hazards are found in the RevPert package tree.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "${ROOT}"
fail=0

echo "[preflight] scanning ${ROOT}"

scan() {
  rg -n "$@" \
    --glob '!docs/run_preflight.sh' \
    --glob '!docs/PRE_UPLOAD_CHECKLIST.md' \
    --glob '!**/*.pdf' \
    --glob '!**/*.png' \
    --glob '!**/*.svg' \
    reverse examples README.md LICENSE requirements.txt environment.yml CITATION.cff docs 2>/dev/null || true
}

hits=$(scan '/home/[a-zA-Z0-9_]+|miniconda3/envs|/Users/[a-zA-Z]')
if [[ -n "${hits}" ]]; then
  echo "${hits}" | head -20
  echo "FAIL: absolute personal paths found"
  fail=1
else
  echo "OK: no absolute personal paths"
fi

hits=$(scan '[\p{Han}]' --glob '*.md' --glob '*.py' --glob '*.sh' --glob '*.yml' --glob '*.txt' || true)
# Fallback if \p{Han} unsupported: use a broad CJK range via perl
if ! rg --pcre2 -q 'a' <<< 'a' 2>/dev/null; then
  hits=$(find reverse examples docs -type f \( -name '*.py' -o -name '*.md' -o -name '*.sh' -o -name '*.yml' -o -name '*.txt' \) -print0 \
    | xargs -0 perl -ne 'print "$ARGV:$.:$_" if /\p{Han}/' 2>/dev/null | head -20 || true)
fi
if [[ -n "${hits}" ]]; then
  echo "${hits}" | head -20
  echo "FAIL: CJK characters found"
  fail=1
else
  echo "OK: no CJK in text sources"
fi

hits=$(scan -i 'api[_-]?key\s*=|secret_key\s*=|BEGIN RSA PRIVATE|huggingface_hub.*token|password\s*=\s*["\047]')
if [[ -n "${hits}" ]]; then
  echo "${hits}" | head -20
  echo "FAIL: possible secrets"
  fail=1
else
  echo "OK: no obvious secrets"
fi

hits=$(scan -i 'chatgpt|claude\.ai|as an ai language|generated by cursor')
if [[ -n "${hits}" ]]; then
  echo "${hits}" | head -20
  echo "FAIL: AI boilerplate traces"
  fail=1
else
  echo "OK: no obvious AI boilerplate"
fi

if find . -iname '*dual_encoder_v2*' | head -5 | grep -q .; then
  echo "FAIL: dual_encoder_v2 artifacts present"
  fail=1
else
  echo "OK: no dual_encoder_v2 tree"
fi

if find . -name '*.pt' -o -name '*.h5ad' | head -5 | grep -q .; then
  echo "WARN: large binary model/data files present (confirm intentional)"
else
  echo "OK: no .pt/.h5ad in tree"
fi

sz=$(du -sm . | awk '{print $1}')
echo "Package size: ${sz} MB"
if (( sz > 500 )); then
  echo "WARN: package > 500 MB; trim before GitHub push"
fi

# Import smoke test
if PYTHONPATH="${ROOT}" python -c "from reverse.src import cell_lines, delta_y_star" 2>/dev/null; then
  echo "OK: python import smoke test"
else
  echo "WARN: python import smoke test failed (missing deps in current env?)"
fi

exit "${fail}"
